# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
# spec:
#   ports:
#   - port: 3306
#   selector:
#     app: mysql
#   clusterIP: None
# ---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-port
    protocol: TCP
  selector:
    app: mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: quay.io/debezium/example-mysql:1.8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: debezium
        - name: MYSQL_USER
          value: kelvin
        - name: MYSQL_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql