apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster-service
spec:
  ports:
  - port: 9010
    targetPort: 9010
    name: kafka-cluster-zookeeper-jmx
  - port: 9011
    targetPort: 9011
    name: kafka-cluster-kafka-jmx
  - port: 9012
    targetPort: 9012
    name: kafka-cluster-connector-jmx
  - port: 8083
    targetPort: 8083
    name: kafka-cluster-connector
  - port: 3223
    targetPort: 3223
    name: kafka-cluster-api-monitor
  - port: 3224
    targetPort: 3224
    name: kafka-cluster-api-monitor-swagger
  selector:
    app: kafka-cluster
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-cluster
  labels:
    app: kafka-cluster 
spec:
  containers:
  - image: lxcinder/jmxdebezium
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: kafka-cluster 
    ports:
    - containerPort: 9010
      name: zookeeperjmx
    - containerPort: 9011
      name: kafkajmx
    - containerPort: 9012
      name: connectorjmx
    - containerPort: 8083
      name: connector
    - containerPort: 3223
      name: api-monitor
    - containerPort: 3224
      name: monitor-swagger