apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-service-open
  name: mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-port
  selector:
    app: mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ZGViZXppdW1zb3VyY2U=
        - name: MYSQL_USER
          value: kelvin
        - name: MYSQL_PASSWORD
          value: ZGViZXppdW1zb3VyY2U=
        ports:
        - containerPort: 3306
          name: mysql