apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elastic-store
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eslatic-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: elastic-store
  resources:
    requests:
      storage: 5Gi
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: elasticsearch-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi