apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqllatest-service-open
  name: mysqllatest-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysqllatest-port
  selector:
    app: mysqllatest
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqllatest
spec:
  selector:
    matchLabels:
      app: mysqllatest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqllatest
    spec:
      containers:
      - image: mysql:latest
        name: mysqllatest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ZGViZXppdW1zb3VyY2U=
        - name: MYSQL_USER
          value: kelvin
        - name: MYSQL_PASSWORD
          value: ZGViZXppdW1zb3VyY2U=
        ports:
        - containerPort: 3306
          name: mysqllatest