kind: Deployment
apiVersion: apps/v1
metadata:
  name: debezium-connector-jdbc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connector-jdbc-es
  template:
    metadata:
      labels:
        app: debezium-connector-jdbc-es
        id: "0"
    spec:
      containers:
      - name: debezium-connector-jdbc-es
        image: debeziumdev.azurecr.io/debezium-connect-cluster:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8083
        env:
          - name: BOOTSTRAP_SERVERS
            value: "debeziumdev-kafka-bootstrap:9092"
          - name: GROUP_ID
            value: "2"
          - name: CONFIG_STORAGE_TOPIC
            value: "my_connect_configs"
          - name: OFFSET_STORAGE_TOPIC
            value: "my_connect_offsets"
          - name: STATUS_STORAGE_TOPIC
            value: "my_source_connect_statuses"
          - name: KAFKA_OPTS
            value: "-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml"
          - name: JMXHOST
            value: "0.0.0.0"
          - name: JMXPORT
            value: "2976"
      imagePullSecrets: 
      -  name: debeziumsecret
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: debezium-connector-jdbc-es
#   name: connector-service
# spec:
#   ports:
#   - port: 2976
#     targetPort: 2976
#     name: connector-port
#     protocol: TCP
#   selector:
#     app: debezium-connector-jdbc-es
#   type: LoadBalancer