version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
     - 9010:9010
    environment:
     - JMXPORT=9010
     - JMXHOST=0.0.0.0
  kafka:
    image: quay.io/debezium/kafka:1.9
    ports:
     - 29092:9092
     - 9011:9011
    links:
     - zookeeper
    environment:
     - KAFKA_BROKER_ID=1
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
     - KAFKA_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
     - JMXPORT=9011
     - JMXHOST=0.0.0.0

  connect:
    image: debezium/connect
    build:
      context: .
    ports:
     - 8083:8083
     - 9012:9012
    links:
     - kafka
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://connect:8083/connectors || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 3
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses 
      - JMXHOST=0.0.0.0
      - JMXPORT=9012