apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: index
  name: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - image: index:latest
        imagePullPolicy: Never
        name: index
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: index-service
  name: index-service
spec:
  selector:
    app: index   
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 30003