apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "2132"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "192.168.2.15:30081"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://:9092,PLAINTEXT_HOST://192.168.2.15:8092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,PLAINTEXT_HOST://192.168.2.15:8092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "30081"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
spec:
  selector:
    app: kafka
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8092
    targetPort: 9092
    nodePort: 30092
    