global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  # - job_name: kafka-exporter
  #   metrics_path: /metrics
  #   honor_labels: false
  #   honor_timestamps: true
  #   sample_limit: 0
  #   static_configs:
  #     - targets: ['docker.host.internal:9308']

  # - job_name: 'prometheus'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['docker.host.internal:9090']

  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']